#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get install nginx -y
sudo chmod 777 /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
