#!/usr/bin/env bash
#0-custom_http_response-header

sudo apt-get update
sudo apt-get -y install nginx
string2="http {\\n\\tadd_header X-Served-By \'$HOSTNAME\';"
sudo service nginx start

dest="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "22i $dest" /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload
