#!/usr/bin/env bash
# bad luck, 8 is your chance

a=1
while [ $a -le 10 ]
do
if [ $a -eq 4 ]
then
echo "bad luck"
elif [ $a -eq 8 ]
then
echo "good luck"
else
echo "Holberton School"
fi
(( a++ ))
done